<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yrb-PC" name="com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test" tests="1" failures="0" timestamp="4 Aug 2018 03:59:40 GMT" time="14.371" errors="1">
  <testcase name="detailOperator" time="14.371" classname="com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test">
    <error type="java.lang.AssertionError" message="超时!! 10 秒之后还没找到元素 [By.xpath: //*[@id=&quot;app&quot;]//button[contains(text(),&#039;确认&#039;)][1]]">
      <![CDATA[java.lang.AssertionError: 超时!! 10 秒之后还没找到元素 [By.xpath: //*[@id="app"]//button[contains(text(),'确认')][1]]
	at org.testng.Assert.fail(Assert.java:94)
	at com.wymall.test.utils.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:275)
	at com.wymall.test.utils.SeleniumUtil.click(SeleniumUtil.java:135)
	at com.wymall.test.utils.actions.impl.Click.doAction(Click.java:23)
	at com.wymall.test.utils.SuperAction.parseExcel(SuperAction.java:271)
	at com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test.detailOperator(ChildOperatorPage_004_detailOperator_Test.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- detailOperator -->
</testsuite> <!-- com.wymall.test.testcases.childOperator.ChildOperatorPage_004_detailOperator_Test -->
